resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: 8.x


- task: Npm@1
  displayName: 'install gatsby'
  inputs:
    command: custom

    verbose: false

    customCommand: 'install -g gatsby-cli'


- script: |
   npm install
   npx gatsby build
  displayName: 'gatsby build'

- task: CopyFiles@2
  displayName: 'Copy built site'
  inputs:
    SourceFolder: public

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

    CleanTargetFolder: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'





